[project]
name = "arena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Solohiddin", email = "sirojiddinovsolohiddin961@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
arena = "arena:main"

[tool.uv]
package = false
