from django.urls import path

from apps.posts.api.views import (
    AmenityListView,
    AppFeedbackCreateView,
    AppFeedbackListView,
    CategoryListView,
    CommentCreateView,
    CommentListView,
    FavouriteCreateView,
    FavouriteDeleteView,
    FavouriteListView,
    MyPostListView,
    PostCreateView,
    PostDeleteView,
    PostDetailView,
    PostFeedbackListView,
    PostFeedbackUpsertView,
    PostListView,
    PostUpdateView,
)

urlpatterns = [
    path("list/", PostListView.as_view(), name="post_list"),
    path("my-posts/", MyPostListView.as_view(), name="my_post_list"),
    path("create/", PostCreateView.as_view(), name="post_create"),
    path("detail/<int:post_id>/", PostDetailView.as_view(), name="post_detail"),
    path("update/<int:post_id>/", PostUpdateView.as_view(), name="post_update"),
    path("delete/<int:post_id>/", PostDeleteView.as_view(), name="post_delete"),
    path("feedback/list/<int:post_id>/", PostFeedbackListView.as_view(), name="post_feedback_list"),
    path("feedback/upsert/", PostFeedbackUpsertView.as_view(), name="post_feedback_upsert"),
    path("categories/", CategoryListView.as_view(), name="post_category_list"),
    path("amenities/", AmenityListView.as_view(), name="post_amenity_list"),
    path("favourite/", FavouriteListView.as_view(), name="favourite_list"),
    path("favourite/add/", FavouriteCreateView.as_view(), name="favourite_add"),
    path("favourite/remove/<int:post_id>/", FavouriteDeleteView.as_view(), name="favourite_remove"),
    path("comment/list/<int:post_id>/", CommentListView.as_view(), name="comment_list"),
    path("comment/create/", CommentCreateView.as_view(), name="comment_create"),
    path("app-feedback/", AppFeedbackCreateView.as_view(), name="app_feedback_create"),
    path("app-feedback/list/", AppFeedbackListView.as_view(), name="app_feedback_list"),
]
